### ISSUE TITLE
Merge LSL repositories for all editors

### ISSUE THREAD

**Issue by buildersbrewery** [buildersbrewery/linden-scripting-language#2]
### For your information:

Linden Scripting Language (LSL) syntax grammar, syntax highlighting and snippet file repositories have been merged into this one.

---
@Ben-Kaniobi
@CaptainBlagbird
@Dieselchair
@DigDug101
@FunTimeCoding
@Narmoistar
@PumpkinPai
@RayZopf
@WendyStarfall
@craignegrete
@davep
@daveraye
@daviwil
@dazzlesoftware
@digitalfiz
@dutok
@forgottenleaf
@ilioNaglo
@laughingpain
@nobuyukinyuu
@teells
@ssjkriccolo
@Tavren
@geirnoklebye
@BlackWyvern

**Comment by forgottenleaf** [comment]
Thanks for the update.

**Comment by forgottenleaf** [comment]
@buildersbrewery Wouldn't this make it a little difficult publishing an Atom package or something like that?

**Comment by buildersbrewery** [comment]
True, but this single repository makes applying changes to all editor packages easier.

Atom for instance already has [digitalfiz/language-lsl](https://github.com/digitalfiz/language-lsl), so I'll publish pull requests to that.

**Comment by forgottenleaf** [comment]
Ah I see... By the way, since you deleted the other repository, I think we lost @Makopo's helpful comments on how he created his Sublime Text LSL package? I'll see if I can find a cached version or a wayback machine version.

**Comment by forgottenleaf** [comment]
Nope, can't find archived or cached versions of his comments... I guess I'll try and dig through my own browser's cache.

**Comment by buildersbrewery** [comment]
https://github.com/makopo.atom has the first bits.

**Comment by daveraye** [comment]
I've cloned repo to desktop; can you please direct me where to ask for help to setup in VIM? thx

**Comment by buildersbrewery** [comment]
@daveraye have a look at the [vim](https://github.com/buildersbrewery/linden-scripting-language/blob/master/vim/) subfolder.

**Comment by Makopo** [comment]
reposting...

@forgottenleaf Thank you for mentioning my project :) I'll give you a quick walkthrough of my code for now...

The entry point is [generate.sh] (/Makopo/kwdb_to_sublime/blob/master/generate.sh). I here raw download the lsl2dfg/LSL2dfg.py engine and kwdb.xml from kwdb repository and then kick the engine to generate completion files and some contents in the syntax files. I have the templates in [inputs/] (/Makopo/kwdb_to_sublime/tree/master/inputs) folder and the modules in [lsl2dfg/lsloutputs/] (/Makopo/kwdb_to_sublime/tree/master/lsl2dfg/lsloutputs) folder, both of which will be passed to kwdb engine.

The tricky part is, as for the syntax files (*.tmLanguage), instead of creating the syntax files themselves, I actually create the perl scripts, with kwdb engine. After then, I run the resulting scripts to assemble the regex code with Regexp::Assemble. That's why [the generated codes] (/Makopo/sublime-text-lsl/blob/master/lsl.tmLanguage) are quite unreadable. You don't necessarily need to assemble the regex if Atom internally do that...

**Comment by Makopo** [comment]
@forgottenleaf I added above to my [README.md file](/Makopo/kwdb_to_sublime/blob/master/README.md) as well.

**Comment by digitalfiz** [comment]
@buildersbrewery I don't mind keeping the atom package up to date with what you have here every so often.

**Comment by forgottenleaf** [comment]
Many thanks to you again @Makopo.
