### ISSUE TITLE
OBJECT_*

### ISSUE THREAD

**Issue by buildersbrewery** [buildersbrewery/linden-scripting-language#32]
| Flag | (int value) | Description | Length, when [typecast](http://wiki.secondlife.com/wiki/Typecast) to a [string](http://wiki.secondlife.com/wiki/String) | Description |
|---|---|---|---|---|
| `OBJECT_CREATION_TIME` | 36 | Gets object's creation time. | timestamp | string timestamp |
| `OBJECT_SELECT_COUNT` | 37 | ... | count | integer count |
| `OBJECT_SIT_COUNT` | 38 | ... | count | integer count |
| `OBJECT_SELECTED` | \* | Get, if object is selected. | boolean | integer boolean |
| `OBJECT_SAT_UPON` | \* | Get, if object is sat upon. | boolean | integer boolean |
| `OBJECT_REZ_TIME` | \* | Gets object's rez time. | timestamp | string timestamp |
| `OBJECT_RETURN_TIME` | \* | Gets object's return time. | timestamp | string timestamp |

from [`17.08.11.328159`](http://wiki.secondlife.com/wiki/Release_Notes/Second_Life_Server/17#17.08.11.328159)

**Comment by buildersbrewery** [comment]
@Sei-Lisa FYI, the last four are currently "unimplemented" as far as I can tell from testing on a regular Server sim.

**Comment by Sei-Lisa** [comment]
They don't compile and therefore they are not in the database. These names were only present in the titles of the respective feature requests, which LL recklessly copied to the release notes, but the features weren't finally implemented in the way these titles said, and they declined to implement REZ_TIME and RETURN_TIME. I only added the constants that I verified.

**Comment by Sei-Lisa** [comment]
FYI, in kwdb, a status of "unimplemented" does not mean it doesn't exist; it means it doesn't do anything even if it implies that it does something, like in the case of `PRIM_CAST_SHADOWS` or `llPointAt`. It's different from "deprecated" because deprecated stuff typically does something, like `ATTACH_LPEC` or `llSound`, just not what it's intended or not so well as its non-deprecated versions.

I've always been on the fence about whether it's that useful to distinguish them. IIRC the distinction first came from GeSHi.

**Comment by Sei-Lisa** [comment]
Mazidox Linden has corrected the release notes just today, changing the title of the feature requests to the actual constants implemented. http://wiki.secondlife.com/w/index.php?title=Release_Notes/Second_Life_RC_Magnum/17&curid=207137&diff=1206303&oldid=1206300
