### ISSUE TITLE
color-scheme issues in sublime text

### ISSUE THREAD

**Issue by dialupdisaster** [buildersbrewery/linden-scripting-language#7]
The color-scheme included with the sublime text syntax makes it so unless you have a light theme it clashes really bad.

I would suggest removing it or adding a dark version for those with dark schemes.

![with theme](http://i.imgur.com/fRcURtM.png)

![without theme](http://i.imgur.com/6YDQXMo.png)

**Comment by buildersbrewery** [comment]
Images above as preview below:

---

![with theme](http://i.imgur.com/fRcURtM.png)

![without theme](http://i.imgur.com/6YDQXMo.png)

**Comment by buildersbrewery** [comment]
As you can assign whatever colors you want in the Second Life Viewer now, it probably won't really matter to make schemes anymore. The optional scheme included was to replicate the old viewer style.

Haven't been online in a long time, but I believe the default color palette has changed since (introducing the ability described above), as well?!

**Comment by buildersbrewery** [comment]
@digitalfiz you can disable the scheme via `Preferences > Package Settings > LSL > Use LindenLab viewer theme`

(...should rename that btw)
